(function(){'use strict';var data=null,diceState={devices:[],countdowns:{}},es=null,actionSelection=[],actionKey='',roleDraft={},chatCollapsed=false,refreshTimer=null,refreshType=null,lobbyLoading=false,lobbyReloadPending=false,readySubmitting=false,pitcherRollSubmitting=false,attackBoostSubmitting=false,gameLoading=false;
function announceRule(rule,occurrence){if(window.GameRules)window.GameRules.announce(rule,String(occurrence));}
  function fetchWithTimeout(path,options){var controller=typeof AbortController==='function'?new AbortController():null,timer=controller?setTimeout(function(){controller.abort();},10000):null,requestOptions=options||{};if(controller)requestOptions.signal=controller.signal;return fetch(path,requestOptions).catch(function(error){if(error&&error.name==='AbortError')throw new Error('请求超时，请检查网络后重试');throw error;}).finally(function(){if(timer)clearTimeout(timer);});}
  function api(path,method,body){return fetchWithTimeout(path,{method:method||'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}).then(function(r){return r.json().catch(function(){return{}}).then(function(d){if(r.status===401)location.replace('/login');if(!r.ok)throw new Error(d.error||'操作失败');return d;});});}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function renderAfkState(){if(!data)return;var me=data.me,team=data.teams.find(function(item){return item.id===me.teamId;}),box=document.getElementById('afk-notice');if(!box){box=document.createElement('section');box.id='afk-notice';var room=document.getElementById('my-team');room.parentNode.insertBefore(box,room);}var afkMembers=team?team.members.filter(function(member){return member.afk;}):[];if(!afkMembers.length){box.className='afk-notice hidden';box.innerHTML='';return;}var names=afkMembers.map(function(member){return esc(member.originalDisplayName||member.displayName);}).join('、');box.className='afk-notice '+(me.afk?'is-self':'is-team');box.innerHTML=me.afk?'<div><small>AFK MODE · 已由系统托管</small><b>你当前被标记为挂机</b><p>挂机期间不能投票、担任核心角色或进入出战阵容。返回后请先取消挂机。</p></div><button id="cancel-afk" class="btn btn-primary">取消挂机，恢复参与</button>':'<div><small>TEAM AVAILABILITY</small><b>本队挂机成员：'+names+'</b><p>挂机成员已由系统托管，不会出现在角色投票和队长选择出战阵容的候选名单中。</p></div>';document.querySelectorAll('#my-team .teammate').forEach(function(node,index){var member=team.members[index];if(!member||!member.afk)return;node.classList.add('afk');var name=node.querySelector('b');if(name&&!name.querySelector('.teammate-afk-tag'))name.insertAdjacentHTML('beforeend','<em class="teammate-afk-tag">挂机</em>');var status=node.lastElementChild;if(status)status.textContent='AFK';});var cancel=document.getElementById('cancel-afk');if(cancel)cancel.onclick=function(){cancel.disabled=true;cancel.textContent='正在恢复…';api('/api/lobby/afk/cancel','POST',{}).then(load).catch(function(error){cancel.disabled=false;cancel.textContent='取消挂机，恢复参与';window.alert(error.message);});};}
function opponentRosterHtml(team){if(!team||!team.members||!team.members.length)return'';return'<section class="opponent-roster"><div class="opponent-roster-head"><div><small>OPPONENT ROSTER · '+team.members.length+'/30</small><h3>'+esc(team.name)+'</h3></div><span>本场对手</span></div><div class="opponent-roster-grid">'+team.members.map(function(user){var managed=user.standIn?' · 托管':user.afk?' · 挂机':'';return'<div class="opponent-member '+(user.afk?'is-afk':'')+'"><b>'+esc(user.originalDisplayName||user.displayName)+'</b><span>'+esc(user.department)+'</span><i>'+(user.frontEnd?'前端':'后端')+managed+'</i></div>';}).join('')+'</div></section>';}
function render(){var me=data.me,team=data.teams.find(function(t){return t.id===me.teamId;}),opponent=data.teams.find(function(t){return t.id!==me.teamId&&t.id!=='spectator'&&t.members&&t.members.length;});document.getElementById('lobby-identity').textContent=me.displayName+' · '+me.department;var phase={PREPARING:'等待管理员分组',GROUPED:'全员准备中',PLAYING:'比赛已经开始',FINISHED:'本轮已结束'}[data.phase];document.getElementById('lobby-hero').innerHTML='<p class="hub-eyebrow">CURRENT SIGNAL</p><h1>'+phase+'</h1><p>'+(team?'你已进入 '+esc(team.name)+'，请确认队友并完成准备。':'你暂未进入本轮分组，当前处于观战席。')+'</p>';var room=document.getElementById('my-team'),chat=document.getElementById('team-chat');if(team){var canReady=!!data.canReady&&!readySubmitting;room.innerHTML='<div class="hub-section-title"><div><small>MY TEAM · '+team.members.length+'/30</small><h2>'+esc(team.name)+'</h2></div><button id="ready-btn" class="btn '+(me.ready?'btn-ghost':'btn-primary')+'" '+(canReady?'':'disabled')+'>'+(readySubmitting?'提交中…':(me.ready?'取消准备':'我已准备'))+'</button></div><div class="teammate-grid">'+team.members.map(function(u){var managed=u.standIn?'<em class="teammate-managed-tag"><i></i>托管</em>':'';return'<div class="teammate '+(u.ready?'ready ':'')+(u.standIn?'managed':'')+'"><b>'+esc(u.originalDisplayName||u.displayName)+managed+'</b><span>'+esc(u.department)+'</span><i>'+(u.standIn?'AUTO':(u.ready?'READY':'WAIT'))+'</i></div>';}).join('')+'</div>'+opponentRosterHtml(opponent);chat.classList.remove('hidden');chat.classList.toggle('chat-docked',data.phase==='PLAYING');chat.classList.toggle('chat-collapsed',chatCollapsed);syncChatToggle();var b=document.getElementById('ready-btn');b.onclick=function(){if(!canReady)return;var nextReady=!me.ready;readySubmitting=true;render();api('/api/lobby/ready','POST',{ready:nextReady}).then(function(){var member=team.members.find(function(user){return user.id===me.id;});data.me.ready=nextReady;if(member)member.ready=nextReady;readySubmitting=false;render();load();}).catch(function(error){readySubmitting=false;render();window.alert(error.message);});};}else{room.innerHTML='<div class="empty-stand"><b>👁 观战席</b><p>管理员将未参赛用户留在观战席，你仍可查看四组实时比分。</p></div>';chat.classList.add('hidden');chat.classList.remove('chat-docked');}document.getElementById('lobby-matches').innerHTML=data.matches.map(function(m){return'<article class="watch-card"><small>GROUP '+m.number+' · 60 人</small><div><b>'+esc(m.nameA)+'</b><strong>'+m.scoreA+' : '+m.scoreB+'</strong><b>'+esc(m.nameB)+'</b></div></article>';}).join('');}
function syncChatToggle(){var button=document.getElementById('chat-toggle');button.textContent=chatCollapsed?'展开':'收起';button.setAttribute('aria-expanded',String(!chatCollapsed));}
function playerAction(type,selections){return api('/api/lobby/player-action','POST',{type:type,selections:selections||[]}).then(function(){actionSelection=[];actionKey='';if(type==='role-vote'&&data&&data.me)delete roleDraft[data.me.teamId];load();});}
function selectionHasBackEnd(players){return players.some(function(p){return actionSelection.indexOf(String(p.id))>=0&&p.role==='back';});}
function selectionReady(type,players){if(actionSelection.length!==5)return false;return type!=='lineup'||selectionHasBackEnd(players);}
function selectionHint(type,players){if(type!=='lineup'||actionSelection.length!==5||selectionHasBackEnd(players))return '';return ' · 还需至少 1 名后端';}
function refreshActionState(type,players){document.getElementById('action-count').textContent=actionSelection.length+' / 5'+selectionHint(type,players);document.getElementById('action-submit').disabled=!selectionReady(type,players);}
function actionChoices(box,title,hint,players,type,key){if(actionKey!==key){actionKey=key;actionSelection=[];}var playerIds=players.map(function(p){return String(p.id);});actionSelection=actionSelection.filter(function(id){return playerIds.indexOf(String(id))>=0;});box.innerHTML='<div class="role-ribbon">玩家操作台</div><div class="hub-section-title"><div><small>'+esc(hint)+'</small><h2>'+esc(title)+'</h2></div><span id="action-count">'+actionSelection.length+' / 5'+selectionHint(type,players)+'</span></div><div class="action-player-grid">'+players.map(function(p){var selected=actionSelection.indexOf(String(p.id))>=0;return'<button class="action-player'+(selected?' selected':'')+'" data-player="'+esc(p.id)+'" aria-pressed="'+selected+'"><b>'+esc(p.name)+'</b><small>'+(p.role==='back'?'后端':'前端')+'</small></button>';}).join('')+'</div><div class="action-footer">'+(type==='prophet'?'<button id="action-skip" class="btn btn-ghost">本局放弃预言</button>':'')+'<button id="action-submit" class="btn btn-primary"'+(selectionReady(type,players)?'':' disabled')+'>密封提交</button></div>';box.querySelectorAll('[data-player]').forEach(function(btn){btn.onclick=function(){var id=btn.dataset.player,i=actionSelection.indexOf(id);if(i>=0)actionSelection.splice(i,1);else if(actionSelection.length<5)actionSelection.push(id);var selected=actionSelection.indexOf(id)>=0;btn.classList.toggle('selected',selected);btn.setAttribute('aria-pressed',String(selected));refreshActionState(type,players);};});document.getElementById('action-submit').onclick=function(){playerAction(type,actionSelection.slice()).catch(showActionError);};var skip=document.getElementById('action-skip');if(skip)skip.onclick=function(){playerAction('prophet',[]).catch(showActionError);};}
function showActionError(e){var box=document.getElementById('player-actions');box.insertAdjacentHTML('beforeend','<p class="login-error">'+esc(e.message)+'</p>');}
function playerName(team,id){var player=(team.players||[]).find(function(item){return item.id===id;});return player?player.name:'待选';}
function timingProgress(match,team,side){var lineup=(match.lineups&&match.lineups[side])||[],rolled=(match.timing&&match.timing['rolledSlots'+side])||[];return'<div class="timing-progress-head"><b>五名出战队员实时进度</b><span>'+rolled.length+' / '+lineup.length+' 已完成</span></div><div class="timing-progress-grid">'+lineup.map(function(id,index){var done=rolled.indexOf(index+1)>=0;return'<div class="timing-progress-seat '+(done?'done':'waiting')+'"><i>'+(index+1)+'</i><b>'+esc(playerName(team,id))+'</b><small>'+(done?'已完成点击':'等待投骰')+'</small></div>';}).join('')+'</div>';}
function voteSeconds(deadline){return Math.max(0,Math.ceil((Number(deadline||Date.now())-Date.now())/1000));}
function voteCountdown(deadline){return'<span class="vote-countdown" data-vote-deadline="'+Number(deadline||0)+'">剩余 '+voteSeconds(deadline)+' 秒</span>';}
function updateVoteCountdowns(){document.querySelectorAll('[data-vote-deadline]').forEach(function(node){node.textContent='剩余 '+voteSeconds(node.dataset.voteDeadline)+' 秒';});document.querySelectorAll('[data-boost-deadline]').forEach(function(node){var seconds=voteSeconds(node.dataset.boostDeadline),button=document.getElementById('attack-boost-button');node.textContent='剩余 '+seconds+' 秒';if(seconds<=0&&button){button.disabled=true;button.textContent='领取已结束';}});}
function roleController(gs,team,role){var elected=team.roles&&team.roles[role],assigned=(gs.sandboxPlayers||[]).filter(function(player){return player.teamId===team.id;});if(assigned.some(function(player){return player.playerId===elected;}))return elected;return assigned.length?assigned[0].playerId:elected;}
function prophetSummary(match,side,opponent){var guess=match.prophet&&match.prophet[side];if(!Array.isArray(guess))return'';if(!guess.length)return'<div class="prophet-recap is-skipped"><b>本队军师预言</b><span>本局放弃预言</span></div>';return'<div class="prophet-recap"><b>本队军师预言 · 已封存</b><span>'+guess.map(function(id){return esc(playerName(opponent,id));}).join('、')+'</span></div>';}
function prophetResult(match,side,team,opponent){var guess=match.prophet&&match.prophet[side],hit=match.prophetResults&&match.prophetResults[side];var detail=!Array.isArray(guess)||!guess.length?'未预言':guess.map(function(id){return esc(playerName(opponent,id));}).join('、');return'<div class="prophet-result '+(hit?'is-hit':'')+'"><b>'+esc(team.name)+'军师</b><span>'+detail+'</span><strong>'+(!Array.isArray(guess)||!guess.length?'未预言':hit?'预言命中 · 攻击 +2':'预言未命中')+'</strong></div>';}
function roleVotePanel(box,team){
  var voterId='u'+data.me.id,stage=team.roleVoteStage||'captain',allVotes=team.roleVotes||{},votes=allVotes[stage]||{},roles=team.roles||{},labels={captain:'队长',strategist:'军师',pitcher:'王牌投手'},hints={captain:'仅前端队员可当选',strategist:'负责本局预言',pitcher:'仅后端队员可当选'},order=['captain','strategist','pitcher'],step=Math.max(0,order.indexOf(stage)),elected=Object.keys(roles).map(function(role){return roles[role];}),candidates=team.players.filter(function(p){if(elected.indexOf(p.id)>=0)return false;if(stage==='captain')return p.role!=='back';if(stage==='pitcher')return p.role==='back';return true;}),draft=roleDraft[team.id]||{},selected=candidates.some(function(p){return p.id===draft[stage];})?draft[stage]:(candidates[0]&&candidates[0].id);
  var progress='<div class="role-election-order">'+order.map(function(role,index){return'<span class="'+(index<step?'done':index===step?'active':'')+'">'+(index+1)+' · '+labels[role]+(roles[role]?'：'+esc(playerName(team,roles[role])):'')+'</span>';}).join('<i>→</i>')+'</div>';
  if(votes[voterId]){box.innerHTML='<div class="role-ribbon">核心角色投票 · '+voteCountdown(team.roleVoteDeadlineAt)+'</div>'+progress+'<h2>'+labels[stage]+'选票已密封</h2><p>你的选票已经提交。投票期间不会展示其他队友的提交情况，本阶段结束后系统会自动进入下一名角色。</p>';return;}
  box.innerHTML='<div class="role-ribbon">第 '+(step+1)+' / 3 阶段 · '+voteCountdown(team.roleVoteDeadlineAt)+'</div>'+progress+'<div class="hub-section-title"><div><small>ROLE ELECTION · 匿名投票</small><h2>投票选出'+labels[stage]+'</h2></div></div><div class="role-vote-grid role-vote-single"><label><i>'+labels[stage]+'</i><b>'+hints[stage]+'</b><select id="vote-current-role">'+candidates.map(function(p){return'<option value="'+esc(p.id)+'" '+(p.id===selected?'selected':'')+'>'+esc(p.name)+' · '+(p.role==='back'?'后端':'前端')+'</option>';}).join('')+'</select></label></div><div class="action-footer"><button id="submit-role-vote" class="btn btn-primary" '+(selected?'':'disabled')+'>提交'+labels[stage]+'选票</button></div>';
  var select=document.getElementById('vote-current-role');
  function saveRoleDraft(){roleDraft[team.id]=roleDraft[team.id]||{};roleDraft[team.id][stage]=select.value;}
  select.onchange=saveRoleDraft;
  document.getElementById('submit-role-vote').onclick=function(){saveRoleDraft();playerAction('role-vote',[roleDraft[team.id][stage]]).catch(showActionError);};
}
function roleWaiting(box,title,team,role,controller){box.innerHTML='<div class="role-ribbon">角色权限已锁定</div><h2>'+esc(title)+'</h2><p>本环节由 <b>'+esc(playerName(team,controller||team.roles[role]))+'</b> 操作。你可以继续查看赛况并使用队内频道。</p>';}
function resultSide(team,roll,won){return'<div class="round-result-side '+(won?'is-winner':'')+'"><b>'+esc(team.name)+'</b><div class="round-result-dice">'+((roll&&roll.dice)||[]).map(function(v){return'<i>'+v+'</i>';}).join('')+'</div><strong>'+esc(roll&&roll.finalAttack==null?'-':roll.finalAttack)+'</strong><small>（积累 '+esc(roll&&roll.accumulationAttack||0)+' + 攻擂 '+esc(roll&&roll.attackPhaseAttack||0)+'）× 业绩 '+Number(roll&&roll.growthCoefficient||1).toFixed(4)+' × 盲盒 '+Number(roll&&roll.attackBoostMultiplier||1).toFixed(2)+'</small></div>';}
function resultPanel(match,a,b){var winner=match.roundWinner,seconds=Math.max(0,Math.ceil(((match.resultReadyAt||Date.now())-Date.now())/1000));var verdict=esc((winner==='A'?a:b).name)+' 拿下本场';return'<div class="role-ribbon">单轮攻擂 · 本场结果</div><div class="round-result-board">'+resultSide(a,match.rolls&&match.rolls.A,winner==='A')+'<div class="round-result-verdict"><span>RESULT</span><b>'+verdict+'</b><small>一轮定胜负 · '+match.winsA+' : '+match.winsB+'</small></div>'+resultSide(b,match.rolls&&match.rolls.B,winner==='B')+'</div><div class="prophet-result-grid">'+prophetResult(match,'A',a,b)+prophetResult(match,'B',b,a)+'</div><p class="round-result-next">结果展示中 · 系统约 '+seconds+' 秒后自动进入后续赛程</p>';}
function accumulationPanel(gs,box){
  document.getElementById('attack-ledger').classList.add('hidden');
  var mine=gs.teams.find(function(team){return team.id===data.me.teamId;}),quota=mine.accumulationQuota||0,rolled=mine.accumulationRolled||0,remaining=Math.max(0,quota-rolled),rolling=mine.accumulationRolling||null,allQuota=gs.teams.reduce(function(sum,team){return sum+(team.accumulationQuota||0);},0),allRolled=gs.teams.reduce(function(sum,team){return sum+(team.accumulationRolled||0);},0),dice=mine.accumulationDice||[];
  document.getElementById('lobby-stage-kicker').textContent='第二阶段 · 全队进度';
  document.getElementById('lobby-stage-title').textContent='八队积累期';
  document.getElementById('lobby-matches').innerHTML=gs.teams.map(function(team){
    var q=team.accumulationQuota||0,r=team.accumulationRolled||0,active=team.accumulationRolling;
    return'<article class="watch-card '+(r>=q?'complete':'')+'"><small>'+esc(team.name)+' · GMV ¥'+Number(team.gmv||0).toLocaleString('zh-CN')+'</small><div><b>积累投骰</b><strong>'+r+' / '+q+'</strong><b>'+Number(team.accumulationPoints||0)+' 点</b></div><p>'+(active?esc(active.playerName)+' 掷骰中…':r>=q?'已完成':'剩余 '+Math.max(0,q-r)+' 次')+'</p></article>';
  }).join('');
  var action=rolling?'<div class="accumulation-complete is-rolling"><b>'+esc(rolling.playerName)+' 正在掷积累骰…</b><span>队友正在掷积累骰，请等待本次结果，骰子将在 1～2 秒内揭晓。</span></div>':remaining?'<p>本队还剩 <b>'+remaining+'</b> 次机会。队内任意玩家都可以继续投，必须全部投完。</p><button id="accumulation-roll" class="btn btn-primary btn-xl">投出下一枚积累骰</button>':'<div class="accumulation-complete"><b>本队积累期已完成</b><span>正在等待其他队伍投完，全部完成后系统自动进入攻擂战。</span></div>';
  box.classList.remove('hidden');
  box.innerHTML='<div class="role-ribbon">第二阶段 · 积累期</div><div class="hub-section-title"><div><small>每 100,000 元 GMV = 1 次机会</small><h2>'+esc(mine.name)+'积累投骰</h2></div><span>'+allRolled+' / '+allQuota+'</span></div><div class="accumulation-score"><div><small>赛前一日 GMV</small><b>¥'+Number(mine.gmv||0).toLocaleString('zh-CN')+'</b></div><div><small>本队掷骰进度</small><b>'+rolled+' / '+quota+'</b></div><div><small>累计点数</small><b>'+Number(mine.accumulationPoints||0)+'</b></div></div><div class="accumulation-dice">'+dice.map(function(value,index){return'<i title="第 '+(index+1)+' 次">'+value+'</i>';}).join('')+'</div>'+action;
  var button=document.getElementById('accumulation-roll');
  if(button)button.onclick=function(){button.disabled=true;button.textContent='正在掷骰…';playerAction('accumulation-roll',[]).catch(function(error){button.disabled=false;button.textContent='投出下一枚积累骰';showActionError(error);});};
}
function renderAttackLedger(team,match,side){var ledger=document.getElementById('attack-ledger'),roll=match&&match.rolls&&match.rolls[side],attack=roll&&(roll.attackPhaseAttack==null?roll.attack:roll.attackPhaseAttack),total=roll&&roll.finalAttack,accumulation=Number(team.accumulationPoints||0),coefficient=Number(team.growthCoefficient||1),boost=Number(roll&&roll.attackBoostMultiplier||1);ledger.classList.remove('hidden');ledger.innerHTML='<div><small>积累期攻击贡献 · '+accumulation+' × '+coefficient.toFixed(4)+'</small><strong>'+(accumulation*coefficient).toFixed(2)+'</strong></div><i>+</i><div><small>本轮攻擂攻击贡献'+(attack==null?'':' · '+Number(attack).toFixed(2)+' × '+coefficient.toFixed(4))+'</small><strong>'+(attack==null?'待投骰':(Number(attack)*coefficient).toFixed(2))+'</strong></div><i>=</i><div class="attack-ledger-total"><small>本轮总攻击力'+(total==null?'':' · 盲盒 ×'+boost.toFixed(2))+'</small><strong>'+(total==null?'待生成':Number(total).toFixed(2))+'</strong></div>';}

function attackBoostPanel(){var panel=document.getElementById('attack-boost');if(panel)return panel;panel=document.createElement('section');panel.id='attack-boost';panel.className='hub-card attack-boost-card hidden';var actions=document.getElementById('player-actions');actions.parentNode.insertBefore(panel,actions);return panel;}
function hideAttackBoost(){attackBoostSubmitting=false;attackBoostPanel().classList.add('hidden');}
function renderAttackBoost(match,team,side,myPlayerId,captainController,pitcherController){
  var panel=attackBoostPanel(),boost=match&&match.attackBoost||{},deadline=Number(boost.deadlineAt||0),lineup=match&&match.lineups&&match.lineups[side]||[],claims=boost['claims'+side]||{},claimed=Object.prototype.hasOwnProperty.call(claims,myPlayerId),managed=!!(data&&data.me&&(data.me.afk||data.me.standIn));
  var eligible=match&&match.phase==='ATTACKING'&&deadline>0&&!managed&&myPlayerId!==captainController&&myPlayerId!==pitcherController&&lineup.indexOf(myPlayerId)<0;
  if(!eligible){hideAttackBoost();return;}
  panel.classList.remove('hidden');
  var claimCount=Object.keys(claims).length,expired=Date.now()>=deadline;
  if(claimed){attackBoostSubmitting=false;panel.innerHTML='<div><small>ATTACK BOOST · 本轮助攻</small><h3>攻击力增加盲盒</h3><p>你已为本队领取盲盒，本队当前共有 '+claimCount+' 人完成助攻。</p></div><strong>×'+Number(claims[myPlayerId]).toFixed(2)+'</strong>';return;}
  panel.innerHTML='<div><small>ATTACK BOOST · '+(expired?'领取结束':'<span class="vote-countdown" data-boost-deadline="'+deadline+'">剩余 '+voteSeconds(deadline)+' 秒</span>')+'</small><h3>攻击力增加盲盒</h3><p>'+(expired?'20 秒内未领取，本轮已视为放弃。':'点击随机获得 ×1.00～×1.50，本队已领取倍率取平均后计入总攻击力。')+'</p></div><button id="attack-boost-button" class="btn btn-primary" '+(expired||attackBoostSubmitting?'disabled':'')+'>'+(expired?'领取已结束':attackBoostSubmitting?'开启中…':'开启攻击力盲盒')+'</button>';
  var button=document.getElementById('attack-boost-button');if(button)button.onclick=function(){if(attackBoostSubmitting||Date.now()>=deadline)return;attackBoostSubmitting=true;button.disabled=true;button.textContent='开启中…';playerAction('attack-boost',[]).catch(function(error){attackBoostSubmitting=false;button.disabled=false;button.textContent='开启攻击力盲盒';showActionError(error);});};
}
function tournamentWatchCard(gs,match){var stage=TournamentUI.stage(match),a=gs.teams.find(function(team){return team.id===match.a;}),b=gs.teams.find(function(team){return team.id===match.b;}),winner=gs.teams.find(function(team){return team.id===match.winner;}),detail=match.status==='done'?'胜者 · '+(winner?winner.name:match.winner):match.phase==='RESULT'?'本场结果展示中':'单轮攻擂进行中';return '<article class="watch-card tournament-card '+(match.status==='active'?'is-live':'is-history')+'"><small><span>'+esc(stage.label)+'</span><i>'+TournamentUI.status(match)+'</i></small><div><b>'+esc(a?a.name:match.a)+'</b><strong>'+Number(match.winsA||0)+' : '+Number(match.winsB||0)+'</strong><b>'+esc(b?b.name:match.b)+'</b></div><p>'+esc(detail)+'</p></article>';}
function postMatchPanel(gs,box,match,mine){var won=match.winner===mine.id,champion=gs.champion,stage=TournamentUI.stage(match),all=TournamentUI.matches(gs),sameStage=all.filter(function(item){return TournamentUI.stage(item).rank===stage.rank;}),finished=sameStage.filter(function(item){return item.status==='done';}).length,next=stage.rank===1?'半决赛':stage.rank===2?'总决赛':'本日比赛结束',opponent=gs.teams.find(function(team){return team.id===(match.a===mine.id?match.b:match.a);}),championTeam=gs.teams.find(function(team){return team.id===champion;}),myScore=match.a===mine.id?match.winsA:match.winsB,opponentScore=match.a===mine.id?match.winsB:match.winsA;
  if(champion){var isChampion=champion===mine.id;box.innerHTML='<div class="post-match-state '+(isChampion?'is-champion':'is-spectating')+'"><div class="post-match-signal">'+(isChampion?'🏆':'◉')+'</div><p class="hub-eyebrow">TOURNAMENT COMPLETE</p><h2>'+(isChampion?'恭喜，本日冠军已经产生':'本日赛事已经结束')+'</h2><strong>'+(isChampion?esc(mine.name):'冠军 · '+esc(championTeam?championTeam.name:champion))+'</strong><p>'+(isChampion?'本队完成全部赛程，最终战绩已由服务器保存。':'你可以在下方查看完整赛事结果，战绩已由服务器保存。')+'</p></div>';return;}
  if(won){box.innerHTML='<div class="post-match-state is-waiting"><div class="post-match-signal"><i></i></div><p class="hub-eyebrow">QUALIFIED · WAITING SIGNAL</p><h2>本场获胜，等待其他对阵结束</h2><strong>'+esc(mine.name)+' '+myScore+' : '+opponentScore+' '+esc(opponent?opponent.name:'对手')+'</strong><p>本队已经晋级'+next+'。当前 '+esc(stage.shortLabel)+' '+finished+' / '+sameStage.length+' 场结束，全部结果产生后系统会自动建立下一场对阵，无需刷新页面。</p><div class="post-match-progress"><i style="width:'+Math.round(finished/Math.max(1,sameStage.length)*100)+'%"></i></div><small>等待期间可继续使用左下角队内频道，并在下方查看其他队伍实时赛况。</small></div>';return;}
  box.innerHTML='<div class="post-match-state is-spectating"><div class="post-match-signal">◉</div><p class="hub-eyebrow">MATCH COMPLETE · SPECTATOR MODE</p><h2>本场赛程结束，已转入观战</h2><strong>最终比分 '+myScore+' : '+opponentScore+'</strong><p>对手 '+esc(opponent?opponent.name:'队伍')+' 晋级。你仍可保留队内频道，并在下方观看后续比赛。</p></div>';}
function attackSidePhase(match,side){
  if(match.sidePhases&&match.sidePhases[side])return match.sidePhases[side];
  var legacy=match.phase;
  if(side==='A'){
    if(legacy==='CONFIRM_A')return'CONFIRM';
    if(legacy==='ROLL_A')return'ROLL';
    if(legacy==='PITCHER_ROLL_A')return'PITCHER_ROLL';
    if(legacy==='CONFIRM_B'||legacy==='ROLL_B'||legacy==='PITCHER_ROLL_B')return'WAITING';
  }else{
    if(legacy==='CONFIRM_B'||legacy==='CONFIRM_A'||legacy==='ROLL_A'||legacy==='PITCHER_ROLL_A')return'CONFIRM';
    if(legacy==='ROLL_B')return'ROLL';
    if(legacy==='PITCHER_ROLL_B')return'PITCHER_ROLL';
  }
  return null;
}
function battleReadyPanel(match,team,side,myPlayerId,captainController){
  var lineup=match.lineups&&match.lineups[side]||[],devices=diceState.devices||[],readyCount=0;
  var cards=lineup.map(function(id,index){var device=devices.find(function(item){return item.teamId===team.id&&item.playerId===id&&item.slot===index+1;}),ready=!!(device&&device.ready);if(ready)readyCount++;return'<div class="battle-ready-seat '+(ready?'is-ready':'')+'"><i>'+(index+1)+'</i><b>'+esc(playerName(team,id))+'</b><small>'+(ready?'已准备':device&&device.calibrated?'等待本人准备':'正在进入备战席')+'</small></div>';}).join('');
  var isCaptain=captainController===myPlayerId,allReady=readyCount===5;
  return'<div class="battle-ready-head"><div><small>五人备战状态</small><strong>'+readyCount+' / 5</strong></div><span>'+(allReady?'全员准备完毕':'等待出战队员')+'</span></div><div class="battle-ready-grid">'+cards+'</div>'+(isCaptain?'<div class="action-footer"><button id="captain-command" class="btn btn-primary btn-xl" '+(allReady?'':'disabled')+'>'+(allReady?'队长发号施令':'等待五人全部准备')+'</button></div>':'<p class="timing-spectator-note">五人全部准备后，由队长发号施令。</p>');
}
function renderParallel(gs,box){
  if(gs.stage==='ACCUMULATION'){hideAttackBoost();announceRule('ACCUMULATION',(gs.startedAt||'game')+'-'+data.me.teamId+'-ACCUMULATION');accumulationPanel(gs,box);return;}
  document.getElementById('lobby-stage-kicker').textContent=gs.stage==='ROLE_VOTE'?'第一阶段 · 核心角色投票':'第三阶段 · 当前对阵优先';document.getElementById('lobby-stage-title').textContent=gs.stage==='ROLE_VOTE'?'依次选出队长、军师、王牌投手':'当前赛程 · '+TournamentUI.currentStage(gs);
  var matches=Object.keys(gs.matches||{}).map(function(k){return gs.matches[k];});
  document.getElementById('lobby-matches').innerHTML=TournamentUI.matches(gs).map(function(item){return tournamentWatchCard(gs,item);}).join('');
  var match=matches.find(function(m){return m.status==='active'&&(m.a===data.me.teamId||m.b===data.me.teamId);})||matches.slice().reverse().find(function(m){return m.a===data.me.teamId||m.b===data.me.teamId;});
  if(!match){hideAttackBoost();box.classList.add('hidden');document.getElementById('attack-ledger').classList.add('hidden');return;}
  box.classList.remove('hidden');
  var side=match.a===data.me.teamId?'A':'B',mine=gs.teams.find(function(t){return t.id===data.me.teamId;}),opp=gs.teams.find(function(t){return t.id===(side==='A'?match.b:match.a);});
  mine.players=(mine.players||[]).filter(function(player){return !player.managed;});
  opp.players=(opp.players||[]).filter(function(player){return !player.managed;});
  renderAttackLedger(mine,match,side);
  var submitted=match.submitted||{},phase=match.phase,key=match.id+'-'+match.round,sandboxPlayers=gs.sandboxPlayers||[],solo=sandboxPlayers.some(function(player){return player.username===data.me.username;})||(gs.sandboxSolo&&gs.sandboxSolo.username===data.me.username);
  var myPlayerId='u'+data.me.id,strategistController=roleController(gs,mine,'strategist'),captainController=roleController(gs,mine,'captain'),pitcherController=roleController(gs,mine,'pitcher'),prediction=prophetSummary(match,side,opp);
  renderAttackBoost(match,mine,side,myPlayerId,captainController,pitcherController);
  if(!mine.roles||!mine.roles.captain||!mine.roles.strategist||!mine.roles.pitcher){var roleStage=(mine.roleVoteStage||'captain').toUpperCase();announceRule('ROLE_'+roleStage,(gs.startedAt||'game')+'-'+mine.id+'-ROLE-'+roleStage);roleVotePanel(box,mine);return;}
  if(gs.stage==='ROLE_VOTE'){box.innerHTML='<div class="role-ribbon">核心角色投票 · 本队已完成</div><h2>本队三名核心角色已经产生</h2><p>正在等待其他队伍完成匿名投票。八支队伍全部完成后，系统才会统一进入积累期。</p>';return;}
  var sidePhase=attackSidePhase(match,side),otherSide=side==='A'?'B':'A',opponentPhase=attackSidePhase(match,otherSide);
  if(sidePhase!=='PITCHER_ROLL')pitcherRollSubmitting=false;
  var phaseRule=phase==='PROPHET'?'PROPHET':phase==='LINEUP'?'LINEUP':sidePhase==='PREPARING'||sidePhase==='COUNTDOWN'?'CONFIRM':sidePhase==='ROLL'?'TIMING':sidePhase==='PITCHER_ROLL'?'PITCHER_ROLL':phase==='RESULT'?'RESULT':null;
  if(phaseRule)announceRule(phaseRule,(gs.startedAt||'game')+'-'+match.id+'-'+match.round+'-'+phase+'-'+sidePhase);
  if(phase==='RESULT'){box.innerHTML=resultPanel(match,gs.teams.find(function(t){return t.id===match.a;}),gs.teams.find(function(t){return t.id===match.b;}));return;}
  if(phase==='PROPHET'){var prophetClock=voteCountdown(match.prophetDeadlineAt);if(submitted['prophet'+side])box.innerHTML='<div class="role-ribbon">军师预言 · '+prophetClock+'</div><h2>预言已密封提交</h2><p>系统将在双方提交或 30 秒倒计时结束后自动进入阵容阶段。</p>'+prediction;else if(strategistController!==myPlayerId){roleWaiting(box,'等待本队军师提交预言',mine,'strategist',strategistController);box.querySelector('.role-ribbon').insertAdjacentHTML('beforeend',' · '+prophetClock);}else{actionChoices(box,'军师预言',solo?'沙盘军师操作由你代行；30 秒内未提交将自动放弃':'请在 30 秒内选择对方可能出战的 5 人，超时视为放弃',opp.players,'prophet',key+'-prophet');box.querySelector('.role-ribbon').insertAdjacentHTML('beforeend',' · '+prophetClock);}return;}
  if(phase==='LINEUP'){if(submitted['lineup'+side]){var elected=(match.lineups&&match.lineups[side]||[]).map(function(id){return esc(playerName(mine,id));}).join('、');box.innerHTML='<div class="role-ribbon">队长选定阵容 · 已完成</div><h2>本轮出战 5 人已经确定</h2><p>'+elected+'</p><small>正在等待对方队长完成阵容选择。</small>'+prediction;}else if(captainController!==myPlayerId){roleWaiting(box,'等待本队队长选择本轮出战阵容',mine,'captain',captainController);box.insertAdjacentHTML('beforeend',prediction);}else{actionChoices(box,'队长选择本轮出战 5 人','由队长一人决定 · 必须选择 5 人且至少包含 1 名后端',mine.players,'lineup',key+'-lineup');box.insertAdjacentHTML('beforeend',prediction);}return;}
  var opponentStateLabel={PREPARING:'五人备战准备',COUNTDOWN:'队长已发令',CONFIRM:'准备进攻',ROLL:'五人同步点击',PITCHER_ROLL:'王牌投手投骰',WAITING:'进攻已完成'}[opponentPhase]||'等待流程';
  var opponentStatus='<div class="parallel-opponent-status"><span>对方实时进度</span><b>'+esc(opponentStateLabel)+'</b></div>';
  if(sidePhase==='PREPARING'){
    var lineupIds=match.lineups&&match.lineups[side]||[],displayLeft=Math.max(0,Number(match.lineupDisplayUntil||0)-Date.now());
    if(displayLeft>0){box.innerHTML='<div class="role-ribbon">本局阵容已经确定</div><h2>我方五人出战阵容</h2><div class="lineup-reveal-grid">'+lineupIds.map(function(id,index){return'<div><i>'+(index+1)+'</i><b>'+esc(playerName(mine,id))+'</b></div>';}).join('')+'</div><p>阵容展示结束后，入选队员将自动进入备战席。</p>'+opponentStatus+prediction;setTimeout(loadGameState,Math.min(displayLeft+50,5100));return;}
    if(solo){var sandboxReady=match.sandboxReady&&match.sandboxReady[side]||[];box.innerHTML='<div class="role-ribbon">双人沙盘 · 五人备战</div><h2>依次代行五名出战队员准备</h2><div class="battle-ready-grid">'+lineupIds.map(function(id,index){var ready=sandboxReady.indexOf(id)>=0;return'<button class="battle-ready-seat '+(ready?'is-ready':'')+'" data-sandbox-ready="'+esc(id)+'" '+(ready?'disabled':'')+'><i>'+(index+1)+'</i><b>'+esc(playerName(mine,id))+'</b><small>'+(ready?'已准备':'代行准备')+'</small></button>';}).join('')+'</div><div class="action-footer"><button id="captain-command" class="btn btn-primary btn-xl" '+(sandboxReady.length===5?'':'disabled')+'>队长发号施令</button></div>'+opponentStatus+prediction;box.querySelectorAll('[data-sandbox-ready]').forEach(function(button){button.onclick=function(){button.disabled=true;playerAction('sandbox-ready',[button.dataset.sandboxReady]).catch(function(error){button.disabled=false;showActionError(error);});};});var sandboxCommand=document.getElementById('captain-command');sandboxCommand.onclick=function(){sandboxCommand.disabled=true;playerAction('captain-command',[]).catch(function(error){sandboxCommand.disabled=false;showActionError(error);});};return;}
    if(lineupIds.indexOf(myPlayerId)>=0){location.replace('/player');return;}
    box.innerHTML='<div class="role-ribbon">双方并行攻擂 · 五人备战</div><h2>'+esc(mine.name)+' 等待发令</h2><p>入选队员会自动进入备战席并主动确认准备；其他队员可以在此查看五人的实时状态。</p>'+battleReadyPanel(match,mine,side,myPlayerId,captainController)+opponentStatus+prediction;
    var command=document.getElementById('captain-command');if(command)command.onclick=function(){command.disabled=true;playerAction('captain-command',[]).catch(function(error){command.disabled=false;showActionError(error);});};return;
  }
  if(sidePhase==='COUNTDOWN'){
    var until=Number(match.countdownUntil&&match.countdownUntil[side]||diceState.countdowns&&diceState.countdowns[mine.id]||Date.now()+3000),seconds=Math.max(0,Math.ceil((until-Date.now())/1000));
    box.innerHTML='<div class="battle-countdown"><small>队长已经发令</small><strong>'+seconds+'</strong><p>倒计时结束后，五名出战队员同时点击进攻。</p></div>'+opponentStatus+prediction;setTimeout(loadGameState,250);return;
  }
  if(sidePhase==='CONFIRM'){
    var sync=match.sync||{},captain=!!sync['captain'+side],pitcher=!!sync['pitcher'+side];
    if(!captain&&captainController!==myPlayerId){roleWaiting(box,'等待队长确认进攻',mine,'captain',captainController);box.insertAdjacentHTML('beforeend',prediction);return;}
    if(captain&&!pitcher&&pitcherController!==myPlayerId){roleWaiting(box,'等待王牌投手确认接令',mine,'pitcher',pitcherController);box.insertAdjacentHTML('beforeend',prediction);return;}
    var confirmCopy=solo?'双人沙盘已启用：同队任一玩家可依次完成队长和投手确认。':'5 名出战玩家可先打开掷骰端。队长和投手确认后，系统会等待 5 台设备全部校准。';
    box.innerHTML='<div class="role-ribbon">'+(solo?'双人沙盘 · 角色代行':'双方并行攻擂 · 本队准备')+'</div><h2>'+esc(mine.name)+' 准备进攻</h2><p>'+confirmCopy+'</p>'+opponentStatus+'<div class="action-footer">'+(solo?'':'<a class="btn btn-ghost" href="/player">五名出战队员进入投骰席位</a>')+'<button id="captain-ready" class="btn btn-primary" '+(captain?'disabled':'')+'>'+(captain?'队长已准备':'队长：准备进攻')+'</button><button id="pitcher-ready" class="btn btn-primary" '+(!captain||pitcher?'disabled':'')+'>'+(pitcher?'投手已确认':'投手：收到')+'</button></div>'+prediction;
    document.getElementById('captain-ready').onclick=function(){playerAction('captain-ready',[]).catch(showActionError);};
    document.getElementById('pitcher-ready').onclick=function(){playerAction('pitcher-ready',[]).catch(showActionError);};return;
  }
  if(sidePhase==='ROLL'){
    if(solo){var lineup=(match.lineups&&match.lineups[side])||[],rolled=(match.sandboxRolled&&match.sandboxRolled[side])||[];box.innerHTML='<div class="role-ribbon">沙盘代行 · 五个同步点击席位</div><h2>五名出战队员完成同步点击</h2><p>这些按钮只记录五个操作时间，不会直接生成骰子。五人全部点击后再由王牌投手完成最终投骰。</p>'+opponentStatus+'<div class="sandbox-dice-lineup">'+lineup.map(function(id,index){var done=rolled.indexOf(id)>=0;return'<button class="sandbox-dice-seat '+(done?'rolled':'')+'" data-sandbox-roller="'+esc(id)+'" '+(done?'disabled':'')+'><i>'+(index+1)+'</i><b>'+esc(playerName(mine,id))+'</b><small>'+(done?'已完成点击':'代行同步点击')+'</small></button>';}).join('')+'</div>'+prediction;box.querySelectorAll('[data-sandbox-roller]').forEach(function(button){button.onclick=function(){button.disabled=true;playerAction('sandbox-roll',[button.dataset.sandboxRoller]).catch(function(error){button.disabled=false;showActionError(error);});};});return;}
    var progress=timingProgress(match,mine,side),myLineup=(match.lineups&&match.lineups[side])||[],canRoll=myLineup.indexOf(myPlayerId)>=0;
    if(canRoll){location.replace('/player');return;}
    box.innerHTML='<div class="role-ribbon">双方并行攻擂 · 五人同步点击</div><h2>本队进入默契计时阶段</h2><p>五名出战队员正在各自的备战席完成同步进攻，其他队员可以在这里实时查看点击进度。</p><div class="pl-sync-rule"><b>同步操作规则</b><span>系统记录五名出战队员的点击时间，若最大误差在 0.5 秒以内，本局攻击力 ×1.5；否则使用原始攻击力，无惩罚。</span></div>'+opponentStatus+progress+'<p class="timing-spectator-note">你不在本局五人阵容中，可在此实时观看队友的进攻进度。</p>'+prediction;return;
  }
  if(sidePhase==='PITCHER_ROLL'){
    var timing=match.timing||{},syncOk=!!timing['syncOk'+side],spread=timing['spreadMs'+side],revealPending=!!((match.sync||{})['revealPending'+side])||pitcherRollSubmitting;
    if(pitcherController!==myPlayerId){roleWaiting(box,'五人同步点击完成，等待王牌投手最终投骰',mine,'pitcher',pitcherController);box.insertAdjacentHTML('beforeend','<div class="pl-sync-rule"><b>'+(syncOk?'同步成功 · 攻击力 ×1.5':'未达到 0.5 秒 · 使用原始攻击力')+'</b><span>本次最大操作误差：'+(spread==null?'--':Number(spread).toFixed(0)+' ms')+'</span></div>'+opponentStatus+prediction);return;}
    box.innerHTML='<div class="role-ribbon">双方并行攻擂 · 王牌投手最终投骰</div><h2>五名队员已完成默契计时</h2><div class="pl-sync-rule"><b>'+(syncOk?'同步成功 · 本轮攻击力 ×1.5':'未达到 0.5 秒 · 本轮使用原始攻击力')+'</b><span>最大操作误差：'+(spread==null?'--':Number(spread).toFixed(0)+' ms')+'</span></div>'+opponentStatus+'<p>现在由王牌投手投出本轮最终五枚骰子。</p><div class="action-footer"><button id="pitcher-final-roll" class="btn btn-primary btn-xl" '+(revealPending?'disabled':'')+'>'+(revealPending?'投骰处理中…':'王牌投手：投出五枚骰子')+'</button></div>'+prediction;
    document.getElementById('pitcher-final-roll').onclick=function(){
      if(pitcherRollSubmitting||this.disabled)return;
      pitcherRollSubmitting=true;this.disabled=true;this.textContent='投骰处理中…';
      playerAction('pitcher-roll',[]).catch(function(error){pitcherRollSubmitting=false;var button=document.getElementById('pitcher-final-roll');if(button){button.disabled=false;button.textContent='王牌投手：投出五枚骰子';}showActionError(error);});
    };
    return;
  }
  if(sidePhase==='WAITING'){var completedRoll=match.rolls&&match.rolls[side]||{},completedDice=completedRoll.dice||[];box.innerHTML='<div class="role-ribbon">本队进攻完成 · 等待对方</div><h2>本队已完成最终投骰</h2><div class="waiting-dice-result">'+completedDice.map(function(value){return'<i>'+Number(value)+'</i>';}).join('')+'</div><strong>当前攻擂攻击力 '+Number(completedRoll.attack||0).toFixed(2)+'</strong><p>对方完成进攻后，系统会立即比较双方总攻击力并公布胜负。</p>'+opponentStatus+prediction;return;
  }
  postMatchPanel(gs,box,match,mine);
}
function renderPlayerActions(gs){var box=document.getElementById('player-actions'),ledger=document.getElementById('attack-ledger');if(gs&&gs.stage==='ACCUMULATION'&&data&&!data.me.teamId){hideAttackBoost();ledger.classList.add('hidden');document.getElementById('lobby-stage-kicker').textContent='第一阶段 · 观战';document.getElementById('lobby-stage-title').textContent='八队积累期';document.getElementById('lobby-matches').innerHTML=gs.teams.map(function(team){var q=team.accumulationQuota||0,r=team.accumulationRolled||0;return'<article class="watch-card '+(r>=q?'complete':'')+'"><small>'+esc(team.name)+'</small><div><b>积累投骰</b><strong>'+r+' / '+q+'</strong><b>'+Number(team.accumulationPoints||0)+' 点</b></div></article>';}).join('');box.classList.add('hidden');return;}if(!data||!data.me.teamId||!gs||(data.phase!=='PLAYING'&&!(data.phase==='FINISHED'&&gs.champion))){hideAttackBoost();box.classList.add('hidden');ledger.classList.add('hidden');return;}if(gs.mode==='parallel'){renderParallel(gs,box);return;}hideAttackBoost();if(!gs.live){box.classList.add('hidden');ledger.classList.add('hidden');return;}box.classList.remove('hidden');var live=gs.live,match=gs.matches&&gs.matches[live.matchId];if(!match){box.innerHTML='<p>等待主持人建立比赛。</p>';return;}var side=match.a===data.me.teamId?'A':match.b===data.me.teamId?'B':null;if(!side){box.innerHTML='<div class="role-ribbon">观战模式</div><h2>当前是其他队伍的比赛</h2><p class="dim">你可以继续查看比分和队内聊天，轮到本队时操作台会自动解锁。</p>';return;}var mine=gs.teams.find(function(t){return t.id===data.me.teamId;}),opp=gs.teams.find(function(t){return t.id===(side==='A'?match.b:match.a);}),actions=live.playerActions||{};if(live.step==='prophet'){if(actions['prophet'+side])box.innerHTML='<div class="role-ribbon">军师预言</div><h2>预言已密封提交</h2><p>等待对方队伍完成提交，主持人无法查看预言内容。</p>';else actionChoices(box,'军师预言','选择对方本局可能出战的 5 人',opp.players,'prophet',live.matchId+'-'+live.roundNum+'-prophet');return;}box.innerHTML='<div class="role-ribbon">比赛进行中</div><h2>请使用新版并行比赛流程</h2></div>';}
function renderChampionAnnouncement(gs){var box=document.getElementById('champion-announcement');if(!box){box=document.createElement('section');box.id='champion-announcement';box.className='hub-card champion-announcement hidden';var hero=document.getElementById('lobby-hero');hero.parentNode.insertBefore(box,hero.nextSibling);}var results=gs&&gs.dayResults||{},overall=gs&&gs.overallResult;if(overall&&overall.champion){var winner=(overall.standings||[]).find(function(team){return team.id===overall.champion;})||{},entries=[1,2].map(function(day){var result=results['day'+day],team=result&&(result.teams||[]).find(function(item){return item.id===overall.champion;});return team?{day:day,team:team}:null;}).filter(Boolean);box.className='hub-card champion-announcement is-overall';box.innerHTML='<div class="champion-summary"><div class="champion-crown">🏆</div><div><p class="hub-eyebrow">TWO-DAY GRAND CHAMPION</p><h2>两天最终总冠军 · '+esc(winner.name||overall.champion)+'</h2><p>两天累计 <b>'+Number(winner.totalMatchWins||0)+'</b> 场胜利 · 业绩增长率合计 <b>'+Number(winner.totalGrowthRate||0).toFixed(2)+'%</b></p></div></div>'+TournamentUI.resultRosterHtml(entries);return;}var daily=results.day2||results.day1;if(daily&&daily.champion){var team=(daily.teams||[]).find(function(item){return item.id===daily.champion;})||{};box.className='hub-card champion-announcement is-daily';box.innerHTML='<div class="champion-summary"><div class="champion-crown">🏆</div><div><p class="hub-eyebrow">DAY '+Number(daily.day||1)+' CHAMPION</p><h2>今日冠军 · '+esc(team.name||daily.champion)+'</h2><p>今日总决赛已经结束，比赛结果已同步保存。</p></div></div>'+TournamentUI.resultRosterHtml([{day:Number(daily.day||1),team:team}]);return;}box.className='hub-card champion-announcement hidden';box.innerHTML='';}
function loadGameState(){if(gameLoading)return;gameLoading=true;Promise.all([fetch('/api/game-state').then(function(r){return r.status===204?null:r.json();}),fetch('/api/state').then(function(r){return r.ok?r.json():{devices:[],countdowns:{}};})]).then(function(result){var gs=result[0]&&result[0].state;diceState=result[1]||{devices:[],countdowns:{}};renderChampionAnnouncement(gs);renderPlayerActions(gs);}).catch(function(){}).finally(function(){gameLoading=false;});}
function queueRefresh(type){if(type==='lobby')refreshType='lobby';else if(!refreshType)refreshType='game';if(refreshTimer)return;refreshTimer=setTimeout(function(){var pending=refreshType;refreshTimer=null;refreshType=null;if(pending==='lobby')load();else loadGameState();},150+Math.floor(Math.random()*450));}
function connect(){if(es)es.close();es=new EventSource('/api/lobby/events');es.onopen=function(){queueRefresh('lobby');};es.onmessage=function(e){var m=JSON.parse(e.data);if(m.type==='lobby')queueRefresh('lobby');if(m.type==='game')queueRefresh('game');if(m.type==='chat'){var l=document.getElementById('chat-list');l.insertAdjacentHTML('beforeend','<div class="chat-msg"><b>'+esc(m.sender)+'</b><p>'+esc(m.content)+'</p></div>');l.scrollTop=l.scrollHeight;}};}
function load(){if(lobbyLoading){lobbyReloadPending=true;return;}lobbyLoading=true;api('/api/lobby').then(function(d){var old=data&&data.me.teamId;data=d;document.querySelector('.lobby-shell').classList.toggle('game-active',d.phase==='PLAYING');render();renderAfkState();loadGameState();if(old!==d.me.teamId)connect();}).finally(function(){lobbyLoading=false;if(lobbyReloadPending){lobbyReloadPending=false;load();}});}
document.getElementById('chat-toggle').onclick=function(){chatCollapsed=!chatCollapsed;document.getElementById('team-chat').classList.toggle('chat-collapsed',chatCollapsed);syncChatToggle();};document.getElementById('chat-form').onsubmit=function(e){e.preventDefault();var i=document.getElementById('chat-input');if(!i.value.trim())return;api('/api/lobby/chat','POST',{content:i.value.trim()}).then(function(){i.value='';});};document.getElementById('lobby-logout').onclick=function(){api('/api/auth/logout','POST',{}).finally(function(){location.replace('/login');});};if(window.GameRules)window.GameRules.init();load();connect();setInterval(updateVoteCountdowns,250);})();
